#!/bin/bash

IMAGE=library/mysql:5.7
CONTAINER_NAME=mysql

MYSQL_ROOT_PASSWORD=root-password
MYSQL_DATABASE=db
MYSQL_USER=user
MYSQL_PASSWORD=password

docker create \
    --name $CONTAINER_NAME \
    -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD \
    -e MYSQL_DATABASE=$MYSQL_DATABASE \
    -e MYSQL_USER=$MYSQL_USER \
    -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
    -p 3306:3306 \
    $IMAGE

docker start $CONTAINER_NAME
